### ISSUE TITLE
Request: Change PyPI pkg name to avoid accidentally luring pip-tools users

### ISSUE THREAD

**Issue by AndydeCleyre** [eyalev/pip-tool#1]
Hello!

There's an existing project in PyPI, `pip-tools`, and it looks like some users are mistakenly installing your package `piptool` instead. Those users are using the wrong package name, and nothing seems to be wrong or malicious about your project. Still, I thought I'd ask if you're happy to rename your PyPI package to be something more clearly not `pip-tools`-related.

Thanks for reading!

See also: jazzband/pip-tools#1360

**Comment by eyalev** [comment]
Hi :)

From short googling it seems that there isn't built-in 'rename' option in PyPi. Some articles referred to 'renaming' as changing requirements to depend on another project, and I don't think that will solve your problem.

Please correct me if I'm wrong

**Comment by AndydeCleyre** [comment]
You can delete the package in the web UI, then publish a new package.

**Comment by eyalev** [comment]
Deleted :+1:

**Comment by AndydeCleyre** [comment]
Thanks!
